spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/trippydb?useSSL=false'
    username: 'root'
    password: 'KkKi1%EPZ&BN'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    hibernate:
      ddl-auto: update
